# Generated by Django 3.2.19 on 2023-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_auto_20230612_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestcase',
            name='input_data',
            field=models.TextField(blank=True, verbose_name='input'),
        ),
        migrations.AddField(
            model_name='problemtestcase',
            name='output_data',
            field=models.TextField(blank=True, verbose_name='expected output'),
        ),
    ]
