# Generated by Django 3.2.19 on 2023-06-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_auto_20230612_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemtestcase',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='problemtestcase',
            name='output_data',
        ),
    ]
