# Generated by Django 3.2.19 on 2023-06-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0147_auto_20230612_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTestCaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='input')),
                ('output_data', models.TextField(blank=True, verbose_name='expected output')),
                ('problem_test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='judge.problemtestcase')),
            ],
        ),
    ]
