# Generated by Django 3.2.19 on 2023-07-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_auto_20230612_0623'),
        ('funix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousSubmissionBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Suspicious Behavior Time')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicous_behaviors', to='judge.submission', verbose_name='Suspicious Submission Behavior')),
            ],
        ),
    ]
