# Generated by Django 3.2.19 on 2023-07-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funix', '0002_suspicioussubmissionbehavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspicioussubmissionbehavior',
            name='time',
            field=models.DateTimeField(verbose_name='Suspicious Behavior Time'),
        ),
    ]
