# Generated by Django 3.2.19 on 2023-07-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_auto_20230612_0623'),
        ('funix', '0003_alter_suspicioussubmissionbehavior_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInitialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(default='', max_length=65536, verbose_name='Problem Template Source code')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_code', to='judge.problem')),
            ],
        ),
    ]
